import numpy as np

W = np.load('Weights.npy')

print("1. ^ --> NN   ==>   V_^ + W_NN > \u03F4 | " + "✅" if (W[1] + W[6] > W[10]) else "❌")
print("2. ^ --> DT   ==>   V_^ + W_DT > \u03F4 | " + "✅" if (W[1] + W[7] > W[10]) else "❌")
print("3. ^ --> JJ   ==>   V_^ + W_JJ > \u03F4 | " + "✅" if (W[1] + W[8] > W[10]) else "❌")
print("4. ^ --> OT   ==>   V_^ + W_OT > \u03F4 | " + "✅" if (W[1] + W[9] > W[10]) else "❌")
print("5. DT --> NN   ==>   W + V_DT + W_NN > \u03F4 |", "✅" if (W[0] + W[3] + W[6] > W[10]) else "❌")
print("6. DT --> JJ   ==>   W + V_DT + W_JJ > \u03F4 | " + "✅" if (W[0] + W[3] + W[8] > W[10]) else "❌")
print("7. JJ --> JJ   ==>   V_JJ + W_JJ > \u03F4 | " + "✅" if (W[4] + W[8] > W[10]) else "❌")
print("8. JJ --> JJ   ==>   W + V_JJ + W_JJ > \u03F4 | " + "✅" if (W[0] + W[4] + W[8] > W[10]) else "❌")
print("9. JJ --> NN   ==>   V_JJ + W_NN > \u03F4 | " + "✅" if (W[4] + W[6] > W[10]) else "❌")
print("10. JJ --> NN   ==>  W + V_JJ + W_NN > \u03F4 | " + "✅" if (W[0] + W[4] + W[6] > W[10]) else "❌")
print("11. NN --> OT   ==>   V_NN + W_OT > \u03F4 | " + "✅" if (W[2] + W[9] > W[10]) else "❌")
print("12. NN --> OT   ==>  W + V_NN + W_OT > \u03F4 | " + "✅" if (W[0] + W[2] + W[9] > W[10]) else "❌")
print("13. OT --> NN   ==>   V_OT + W_NN > \u03F4 | " + "✅" if (W[5] + W[6] > W[10]) else "❌")
print("14. OT --> DT   ==>   V_OT + W_DT > \u03F4 | " + "✅" if (W[5] + W[7] > W[10]) else "❌")
print("15. OT --> JJ   ==>   V_OT + W_JJ > \u03F4 | " + "✅" if (W[5] + W[8] > W[10]) else "❌")
print("16. OT --> OT   ==>   V_OT + W_OT > \u03F4 | " + "✅" if (W[5] + W[9] > W[10]) else "❌")